root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/liveboard"
  bin = "./tmp/main"
  args_bin = ["serve"]
  include_ext = ["go", "html", "css", "js"]
  exclude_dir = ["tmp", "vendor", "demo"]
  delay = 500

[log]
  time = false
